### ISSUE TITLE
.\PA280253.ORF [Unsupported]

### ISSUE THREAD

**Issue by Logh0nox** [DavidAnson/ConvertTo-Heic#1]
I tried to convert orf to heic and it said unsopprted, shouldn't work? according to doc it says it's supported

**Comment by DavidAnson** [comment]
You tried to convert an ORF file? That’s not a format I’m familiar with. Do you have a codec installed to support that format? Can you open that file in the Windows Photo app? If not, then this script will not be able to convert it.

**Comment by Logh0nox** [comment]
Yes .ORF like you wrote in the doc, .ORF is a Microsoft Camera Raw Decoder. And yes I can open after I update windows and installed the codec I'm able to open, but the converter always says Unsupported

**Comment by DavidAnson** [comment]
OK, thank you! That is a file format I have never seen, but you are right that it claims to be supported by the raw codec. Does this script work for you if you pass in a different file type like JPEG? Does it fail for all ORF  files, or just one in particular? We could tweak the script to see where it’s failing which might help, but most of the work here is done by other components we don’t have visibility into. If there’s a sample ORF file on the web, I could see if it works on my machine.

**Comment by Logh0nox** [comment]
Thanks for all your help! No actually with JPEG also not working it's strange, but I noticed I'm using the [HEVC Video Extensions from Device Manufacturer](https://www.microsoft.com/en-us/p/hevc-video-extensions-from-device-manufacturer/9n4wgh0z6vhq?ocid=AID2000142_aff_7795_1243925&tduid=(ir__tvmo2w3fykkfrxsmkk0sohz30v2xgspac1m1oj3a00)(7795)(1243925)(je6NUbpObpQ-ITDWvEXH7KcrX5pa8EtDFg)()&ranMID=43674&ranEAID=je6NUbpObpQ&ranSiteID=je6NUbpObpQ-ITDWvEXH7KcrX5pa8EtDFg&epi=je6NUbpObpQ-ITDWvEXH7KcrX5pa8EtDFg&irgwc=1&irclickid=_tvmo2w3fykkfrxsmkk0sohz30v2xgspac1m1oj3a00&activetab=pivot:overviewtab) and not the HEIF and HEVC Media Extensions, you think is due to that?

Btw I uploaded an example .orf photo if you wouldn't mind test it on you side, if it workes I would buy that codec instead.
[.ORF example](https://we.tl/t-Wk6Zymql4U)

**Comment by DavidAnson** [comment]
Could you please try passing the full path to the image file? `C:\dir\file.xyz` I didn’t realize that was necessary, but a bit of testing on my side shows the same failure if I use a relative path like you did in the title of this issue.

**Comment by Logh0nox** [comment]
Yes, you're right, using the full path work on the jpeg photo, but not on the .ORF

**Comment by DavidAnson** [comment]
I tried this on a clean machine and it successfully converted your image after installing both codecs and passing the full path to the file.

**Comment by Logh0nox** [comment]
Both codecs you mean HEIF and HEVC Media Extensions?
Thank you very much for your help :)

**Comment by DavidAnson** [comment]
Yes, the two linked here: https://github.com/DavidAnson/ConvertTo-Heic/blob/master/README.md#requirements
