### ISSUE TITLE
Cant convert CR2 files

### ISSUE THREAD

**Issue by Blair0001** [DavidAnson/ConvertTo-Heic#2]
I just found your script and i am trying to convert a pile of Canon CR2 Raw files into HEIC files. When I try to feed the script all my files it just says everyone of them is unsupported.

![Annotation 2019-11-28 113658](https://user-images.githubusercontent.com/58307033/69825025-68aa8a00-11d3-11ea-92e3-614efce087b0.png)

Any help or suggestions would be helpful. I have downloaded and installed both codecs,

**Comment by DavidAnson** [comment]
1. What command are you running? (See #1 for context on passing the full path.)
2. Does it work for any other file types?

**Comment by Blair0001** [comment]
Talk about Johnny on the spot!

 

I ran the following.   I ended up naming the script file differently than you have it.

 

Get-ChildItem "C:\Users\Manda\Pictures\Wades Wedding\Raw" | .\RawToHEIC.ps1

 

Just tried PNG and failed as well

 

PS C:\Users\blair\Desktop> .\RawToHEIC.ps1 '.\Annotation 2019-11-28 113658.png'

.\Annotation 2019-11-28 113658.png [Unsupported]

 

PS C:\Users\blair\Desktop> .\RawToHEIC.ps1 .\3D4A0728.JPG

.\3D4A0728.JPG [Unsupported]

 

I know I have both required pieces of software installed.  Just installed them and purchased the one from the Microsoft store this morning.

**Comment by DavidAnson** [comment]
Per the other issue, please try passing the full path to the image file. Partial paths are problematic in some cases. (Now that I know, I will try to fix that, but until then full paths are necessary.)

**Comment by Blair0001** [comment]
Got it working.   Also found out it doesn’t seem to like running powershell as admin as well.

 

Also is there an possibility of adding in the option of dumping the new files to a different folder path?

**Comment by DavidAnson** [comment]
Great! Are you OK closing this issue and opening a new one for the option to put into a different directory?

**Comment by Blair0001** [comment]
Yeppers!

 

Sadly I did find that the heic files in windows appeared to be generally larger after about the first 4.  Not sure why, but when converting 838 files, the jpgs took up 8GB+ and the HEIC took up 11GB+.

**Comment by DavidAnson** [comment]
Closing issue per discussion above.
