### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [DavidAnson/ConvertTo-Heic#3]
I am trying to convert a hole folder full of .tif to .heic but i am not able,
I use this command in ps
`dir C:\Users\Juanre7\Desktop\Para_HEIC | .\ConvertTo-Heic.ps1`
but i gen an error, i would really apreciate if you could explain a little more how does it work with folders

**Comment by DavidAnson** [comment]
This is one of the examples in the README and it works in general. What's the error you're getting? Does that folder contain other kinds of files, perhaps?
